# Generated by Django 5.0.4 on 2024-04-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girluser',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='girluser',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
